### ISSUE TITLE
Selection box offset & cosmetic issues

### ISSUE THREAD

**Issue by k-eks** [JLuebben/Floppy#1]
Using Mac OSX Yosemite, master branch from 06.09.16

Selection box:
When draw a selection box and start end end with the mouse at the positions indicated by the red arrows, the resulting box is offset. The effect is larger the further the mouse is away from my monitors center.

Cosmetic:
Node lines are a little bit too low, blue arrow (may requires something similar to the writing offset in the settings menu).
Descriptors of the input in the join node are also off, green arrow.

![screen shot 2016-09-06 at 09 19 28 2](https://cloud.githubusercontent.com/assets/12133169/18265268/109c6fa4-7415-11e6-860c-33826f018869.png)

**Comment by JLuebben** [comment]
Commit #8641013 should fix the alignment of connection and Input/Output icons. The 'Node Font Offset'  setting will now also affect labels which should solve the misalignment issue there, too.

I cannot reproduce the selection box issue on my Linux or Windows machine. I will try to get my hands on a Mac.

**Comment by JLuebben** [comment]
I figured out what is wrong with the box selection. It happens when the painter is zoomed in or out.
I'm working on it.
