### ISSUE TITLE
Feature request: EndNode

### ISSUE THREAD

**Issue by k-eks** [JLuebben/Floppy#12]
A node which kills the interpreter. The idea behind is to have an obvious ending point for the node setup.

**Comment by JLuebben** [comment]
Nodes can now call the self._return(value=0, priority=0) method to explicitly end the graph interpretation.
value can by of any type that has a string representation.
priority can be set to values greater 0 in cases were two nodes are executed simultaneously to define which return value has priority.

Calling the method will cause a pop-up window to appear in the editor notifying the user which node returned which value.

Starting Floppy with the --test <fileName> flag will cause the editor to shut down after hitting a returning node and will the string representation of the return value to stderr in a form like this:
['return value', 'returning node']
