### ISSUE TITLE
Deleting nodes deletes conections

### ISSUE THREAD

**Issue by k-eks** [JLuebben/Floppy#18]
When I load a node setup and delete a node, sometimes this also deletes a seemingly arbitrary number of connections and the can not be re-established. In the node setup shown below, deleting the CreateString node reliable causes this problem but other nodes have done this as well but not reliable.
![screen shot 2016-10-03 at 12 24 29](https://cloud.githubusercontent.com/assets/12133169/19034708/4b46bb90-8965-11e6-8f74-5b6f59ed7201.png)
![screen shot 2016-10-03 at 12 24 40](https://cloud.githubusercontent.com/assets/12133169/19034710/4ead352a-8965-11e6-9b51-cf1533d052f7.png)

**Comment by JLuebben** [comment]
Commit 198e9dc9b932336edc5b2d54edd8db8655c2e7fd should have fixed the issue.
The connections were not really deleted but the note deletion left an wrong reference that caused the paint loop to throw an exception when drawing connections.
