### ISSUE TITLE
ForEach Node has no run function

### ISSUE THREAD

**Issue by k-eks** [JLuebben/Floppy#2]
The forEach node had no run function and did therefore not run properly. I fixed it in my fork 41c5c03

**Comment by JLuebben** [comment]
Are you sure that is needed?
The 'ForEach' Node is almost fully implemented in the 'ForLoop' Node and the 'ForEach' Node worked as expected.
To recycle as much of the Node's code as possible I made the 'ForLoop' Node abstract and reused part of its implementation for the 'ForEachAtomPair' Node. Admittedly not the cleanest solution but I was in a hurry. :)

**Comment by k-eks** [comment]
I think, a simple, non-specific for-each-node is not only handy but important for batch file operations. Here is a quick example:
![screen shot 2016-09-15 at 16 17 13](https://cloud.githubusercontent.com/assets/12133169/18553262/1508bb90-7b60-11e6-8f75-84f29537c03f.png)

**Comment by JLuebben** [comment]
I will re-implement the ForLoop class and its children to make the intended design clearer/cleaner.

**Comment by k-eks** [comment]
I'm not sure if it's a bug or my sloppy re-implementation of the ForEach node but the second ForEach does not trigger the first.

**Comment by JLuebben** [comment]
ForLoops did not consider that the TRIGGER input is optional. 9a69932 should fix that.
