### ISSUE TITLE
Getting Floppy to run for the first time

### ISSUE THREAD

**Issue by skoroneos** [JLuebben/Floppy#22]
Greetings.

I have been trying to get Floppy to run for the first time on an Ubuntu 14.04
After trial and error i *think* i have installed the required packages, as i get no complains for missing packets but when i try to run Floppy from the bin dir i get the following error

~/projects/Floppy$ python3  bin/Floppy.py
Traceback (most recent call last):
  File "bin/Floppy.py", line 4, in <module>
    floppy.main.run()
  File "/home/stelios/projects/Floppy/floppy/main.py", line 22, in run
    startUI(app, painter)
  File "/home/stelios/projects/Floppy/floppy/main.py", line 33, in startUI
    win = MainWindow(painter=painter)
  File "/home/stelios/projects/Floppy/floppy/painter.py", line 785, in __init__
    self.connectHint = self.settings.value('DefaultConnection', type=str)
TypeError: unable to convert a QVariant of type 0 to a QMetaType of type 

Any idea what i am doing wrong ?

**Comment by JLuebben** [comment]
Somehow notifications were turned off for this repository so I did not notice this issue, sorry....

This seems to be a problem with the .INI file used for storing the program's configuration.
Can you try deleting the .INI file?
I also added some code to catch the exception in commit 0f0bcc14d97612f88c4913c4486cd9f022d01182 but I am not sure if the issue re-appears at another place when accessing the .INI file.
