### ISSUE TITLE
Entering values onto nodes: input not aligned with field provided.

### ISSUE THREAD

**Issue by oregon-tony** [JLuebben/Floppy#24]
When you create a string or Int node and try to add a value in the node, the characters you type are not aligned with the actual input field provided. The input characters are showing up "above" the actual input field. See attached screen shot.
![2017-05-29_21-55-57](https://cloud.githubusercontent.com/assets/698153/26568643/f27d797a-44b9-11e7-94bf-ab5c08818a69.png)

**Comment by k-eks** [comment]
When you click on "Settings" (the wrench in the toolbar), look for the "Node Graph Render Settings", there you find the setting "Node Font Offset" to correct for this.
![screen shot 2017-05-30 at 08 56 54](https://cloud.githubusercontent.com/assets/12133169/26571416/2cfa8e2e-4516-11e7-8e23-e3d443a71233.png)

**Comment by JLuebben** [comment]
Currently, the option above is the only way to get a decently looking graph representation.
There seems to be a lot of magic happing which influence the actual size of a font on the screen. And every OS seems to be doing this magic a little bit differently. I tried hard-code presets for all operating systems but once I realized that my Windows tablet does things totally different than my Windows desktop, I decided to put that part into the hands of the users.

If you know a way to query the information necessary to do this automatically from the OS, please let me know.
