### ISSUE TITLE
Set Parameters for Nodes Rather than Inputs and Outputs

### ISSUE THREAD

**Issue by rhingo** [JLuebben/Floppy#25]
Is there a way to set a parameter for a node that is not an input or an output? For example say I wanted to scale and shift my input value linearly in the form y = mx + b. My input is x and my output is y and m (slope) and b (y-intercept) would be parameters of the node. Is there a way to have a user set these parameters already or do nodes only have inputs and outputs?

**Comment by JLuebben** [comment]
I hope I understand you correctly.
If you are absolutely sure that 'm' and 'b' will never need modifying, you can simply hard-code them:
```
def run(self):
   m = 2
   b = 1
   self._y(m*self._x + b)
```

Usually, it is helpful to supply the values for 'm' and 'b' via inputs that have default values. That way you don't need to do anything to get the same behavior but can simply change the values for each instance individually:
```
class ScaleAndShift(Node):
   Input('x', float)
   Input('m', float, default=2)
   Input('b', float, default=1)
   Output('y', float)

   def run():
      self._y(self._m*self._x + self._b)
```
I hope this answers your question.



PS:
In an earlier prototype I used something called 'parameters' - basically 'inputs' that could only be edited by the user directly. No connections to other nodes were possible. I realized that they provide nothing that 'inputs' cannot do already so I removed them.
