### ISSUE TITLE
Error when importing Node: "cannot import name ControlNode"

### ISSUE THREAD

**Issue by theshinyknight** [JLuebben/Floppy#26]
I did download the repo as zip, and added the path to the extracted folder as in the instructions, but when I try to import "Node", I get an error

`from floppy.node import Node`

I get 

```
from floppy.node import ControlNode, Node, MetaNode, SubGraph
ImportError: cannot import name 'ControlNode'
```
How can I fix this? I am on OSX High Sierra.
Also is there any plan for tutorials about how to integrate the visual editor so nodes can be instantiated at runtime while the app is running? Thanks

**Comment by theshinyknight** [comment]
Sure, I am posting the stack trace here.

The steps were 
- Download the zip file
- decompress it and rename the extracted folder
- add the folder path to PYTHONPATH
- open Python3 console and `from floppy.node import Node, Input, Output, Tag, abstractNode,` as described in the readme

Importing floppy works, but when I import from floppy.node, I get the import name error on `ControlNode` 

`>>> from floppy.node import Node, Input, Output, Tag, abstractNode
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../floppy/node.py", line 6, in <module>
    import floppy.graph
  File "...,/floppy/graph.py", line 6, in <module>
    from floppy.node import ControlNode, Node, MetaNode, SubGraph
ImportError: cannot import name 'ControlNode'`

Thanks for looking into the runtime creation of nodes; It would be useful to create nodes at runtime, especially if you are using Floppy as simple action executor.

**Comment by JLuebben** [comment]
I was able to reproduce the issue. My guess it that I have a cyclic dependency in my import statements and importing something 'from floppy.node' does not work if not 'floppy.graph' was imported first.
I will commit a fix soon.

Starting the editor directly via the script 'Floppy.py' in the 'bin' subdirectory should work.

**Comment by theshinyknight** [comment]
Thanks for looking into this; I will give it a spin and see if swapping import statements works.
