### ISSUE TITLE
Delete Connection without deleting Node

### ISSUE THREAD

**Issue by reins-ch** [JLuebben/Floppy#27]
Is there a way to delete a connection between two Nodes without deleting one of the Nodes?
I was not able to select a connection (for editing or deleting).

**Comment by JLuebben** [comment]
Try shift + mouseClick on one of the pins. Ideally on the input pin
involved in that connection, because I cannot know which connection I
should delete if the pin has multiple connections and input pins usually
only have one connection.

**Comment by reins-ch** [comment]
Works perfectly, thank you!
Where do I find the list of all shortcuts?

EDIT: The Shortcut I was looking for is located in floppyUi.py line 262.
Most of the other keyboard-only shortcuts seem to be located in the same file starting at line 1872.

**Comment by JLuebben** [comment]
Unfortunately, I don't have real documentation for that part yet. Most
keyboard short-cuts are defined in initActions(self) in floppyUI.py. But
this does not include the the shift + click shortcut for deleting
connections.
I'll put 'making decent documentation' higher on my to-do list. :)
