### ISSUE TITLE
Cosmetic Issue: List boxes text & selection offset

### ISSUE THREAD

**Issue by k-eks** [JLuebben/Floppy#3]
Text within the selection box has the wrong offset, red arrow.
The selection is also offsetted: When the mouse is at the yellow position, "True" is selected and a little bit below is "False" selected.

![screen shot 2016-09-14 at 16 02 06](https://cloud.githubusercontent.com/assets/12133169/18518517/a2339078-7aa0-11e6-8142-600d999b959d.png)

**Comment by k-eks** [comment]
it worked a little bit too well... now every time I connect something to a list input, the application crashes. Furthermore, I can not select elements in lists other than the first.

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/Users/mydata/projects/Floppy_contribution/floppy/painter.py in paintEvent(self, event)
    505                 if self.graph.getConnectionOfInput(inputPin):
    506                     text = inputPin.name
--> 507                     drawItem.draw(painter, asLabel=text)
    508                     # self.drawLabel(x, y+drawOffset+8, w, h, text, painter, Qt.AlignLeft)
    509                 else:

TypeError: draw() got an unexpected keyword argument 'asLabel'
QPainter::begin: A paint device can only be painted by one painter at a time.
QPainter::setCompositionMode: Painter not active
```

![screen shot 2016-09-15 at 13 06 41](https://cloud.githubusercontent.com/assets/12133169/18547907/2acc6978-7b46-11e6-9ffe-9c8d99b9be46.png)
![screen shot 2016-09-15 at 13 06 49](https://cloud.githubusercontent.com/assets/12133169/18547899/217adc42-7b46-11e6-8f5e-973c993ba69f.png)

**Comment by k-eks** [comment]
I just noticed that this selection problem is more of a display problem. If I click somewhere below the list box, then I can choose False but it will not be highlighted nor shown to be selected.

**Comment by JLuebben** [comment]
73de15c fixes the crash when connecting an input with a Selector widget.
I will investigate why the weird offset issue is still there.
